#!/usr/bin/env bash
# Extract AoU workspace env vars from `wb` into <repo>/.env, and ensure
# ~/.bashrc sources it so future shells inherit the values. Idempotent.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

for cmd in wb jq; do
    command -v "$cmd" >/dev/null \
        || { echo "error: '$cmd' not found in PATH" >&2; exit 1; }
done

echo "Querying AoU workspace via wb..."
workspace_json="$(wb workspace describe --format=json)"
resources_json="$(wb resource list --format=json)"

google_cloud_project="$(jq -r '.googleProjectId' <<<"$workspace_json")"

data_bucket="$(jq -r '.[] | select(.resourceType=="GCS_BUCKET" and .id=="data") | .bucketName' <<<"$resources_json")"
ckpt_bucket="$(jq -r '.[] | select(.resourceType=="GCS_BUCKET" and .id=="ckpt") | .bucketName' <<<"$resources_json")"

workspace_bucket="$(jq -r '.[] | select(.resourceType=="GCS_BUCKET" and (.id | contains("workspace-bucket")) and (.id | contains("temporary") | not)) | .bucketName' <<<"$resources_json")"
workspace_temp_bucket="$(jq -r '.[] | select(.resourceType=="GCS_BUCKET" and (.id | contains("temporary-workspace-bucket"))) | .bucketName' <<<"$resources_json")"

workspace_cdr="$(jq -r '[.[] | select(.resourceType=="BQ_DATASET" or .resourceType=="BIGQUERY_DATASET")][0] | "\(.projectId).\(.datasetId)"' <<<"$resources_json")"

for v in google_cloud_project data_bucket ckpt_bucket workspace_cdr; do
    val="${!v}"
    if [[ -z "$val" || "$val" == "null" ]]; then
        echo "error: failed to resolve $v from wb output" >&2
        exit 1
    fi
done

echo "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Auto-generated by data/aou/setup.sh — re-run to refresh.
export GOOGLE_CLOUD_PROJECT=$google_cloud_project
export WORKSPACE_CDR=$workspace_cdr
export WORKSPACE_BUCKET=gs://$workspace_bucket
export WORKSPACE_TEMP_BUCKET=gs://$workspace_temp_bucket
export DATA_BUCKET=$data_bucket
export CKPT_BUCKET=$ckpt_bucket
export DELPHI_DATA_DIR=gs://$data_bucket
export DELPHI_CKPT_DIR=gs://$ckpt_bucket
EOF

bashrc_line="set -a; source $ENV_FILE; set +a"
if grep -Fxq "$bashrc_line" "$HOME/.bashrc" 2>/dev/null; then
    echo "~/.bashrc already sources $ENV_FILE"
else
    echo "Adding source line to ~/.bashrc"
    {
        echo ""
        echo "# Delphi: auto-load env from repo .env"
        echo "$bashrc_line"
    } >> "$HOME/.bashrc"
fi

echo "Done. New shells will inherit the env vars (or 'source ~/.bashrc' now)."
