batch_size: 128
expansion_packs:
  - family_hx
  - fsf
  - meds
  - ops
  - prescriptions
  - summary_ops
biomarkers:
  - prs
  - wbc
  - lipid
  - lft
  - renal
  - hba1c
  - crp
  - urate
  - cysc
  - apo
  - vitd
  - dht
  - shbg
  - igf1
  - nak
  - creat
  - albu
  - diet
  - met
  - telomere
log:
  run_name: delphi-m4
